import { createSlice } from "@reduxjs/toolkit";
const initialState = {
  dashboard_icon_size: 44,
  dashboard_icon_weight: "duotone",
  dashboard_icon_color: "#352f44",
  totalInfo: {
    TotalStudent: 9600,
    TotalTeacher: 10,
    TotalCourses: 20,
    TotalPendingFees: 36054,
  },
  pendingStudents: [
    {
      id: "1",
      imageSrc: "/StudentImg/student1.png",
      roll_no: "12354",
      course: "B.Sc.(CS)",
      pending_fees: "5000",
      gender: "Male",
      status: false,
      full_name: "John Doe",
    },
    {
      id: "2",
      imageSrc: "/StudentImg/student1.png",
      roll_no: "12355",
      course: "B.Com.",
      pending_fees: "3000",
      gender: "Female",
      status: true,
      full_name: "Jane Smith",
    },
    {
      id: "3",
      imageSrc: "/StudentImg/student1.png",
      roll_no: "12356",
      course: "B.A.",
      pending_fees: "2000",
      gender: "Female",
      status: true,
      full_name: "Alice Johnson",
    },

    {
      id: "4",
      imageSrc: "/StudentImg/student1.png",
      roll_no: "12357",
      course: "B.Com.",
      pending_fees: "3000",
      gender: "Female",
      status: true,
      full_name: "Jane Smith",
    },
    {
      id: "5",
      imageSrc: "/StudentImg/student1.png",
      roll_no: "12356",
      course: "B.A.",
      pending_fees: "2000",
      gender: "Female",
      status: true,
      full_name: "Alice Johnson",
    },
  ],
  logingActivty: [
    {
      DeviceName: "Windows",
      $updatedAt: "10:31 AM",
      LogoutTime: "10:49 AM",
      Date: "12/01/2025",
      clientName: "Arshnoor",
      Status: false,
    },
    {
      DeviceName: "Windows",
      LoginTime: "09:26 AM",
      LogoutTime: "10:49 AM",
      Date: "13/01/2025",
      clientName: "Sarfaraz",
      Status: true,
    },
    {
      DeviceName: "Windows",
      $updatedAt: "10:31 AM",
      LogoutTime: "10:49 AM",
      Date: "12/01/2025",
      clientName: "Arshnoor",
      Status: false,
    },
    {
      DeviceName: "Windows",
      LoginTime: "09:26 AM",
      LogoutTime: "10:49 AM",
      Date: "13/01/2025",
      clientName: "Sarfaraz",
      Status: true,
    },
  ],
};
const dashboardSlice = createSlice({
  name: "dashboard",
  initialState,
});
export default dashboardSlice.reducer;
